/** @type {import('tailwindcss').Config} */

export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    container: {
      center: true,
    },
    extend: {
      colors: {
        primary: {
          DEFAULT: '#7FBEAB',
          50: '#F0F8F5',
          100: '#DCEDE4',
          200: '#A5D4C8',
          500: '#7FBEAB',
          600: '#5EA08C',
          700: '#4A8270',
          light: '#A5D4C8',
          dark: '#5EA08C',
        },
        secondary: {
          DEFAULT: '#F5F0E8',
          50: '#FAF7F2',
          100: '#F5F0E8',
          200: '#E8E0D0',
          light: '#FAF7F2',
          dark: '#E8E0D0',
        },
        accent: {
          DEFAULT: '#E8A87C',
          50: '#FDF3E9',
          100: '#F0C4A8',
          500: '#E8A87C',
          600: '#D08A5C',
          light: '#F0C4A8',
          dark: '#D08A5C',
        },
        // 语义化层
        background: '#FAFAF8',
        surface: '#FFFFFF',
        'surface-muted': '#FAF7F2',
        'surface-hover': '#F5F0E8',
        foreground: '#3D3D3D',
        muted: '#9CA3AF',
        'muted-foreground': '#6B7280',
        border: '#EFEAE0',
        'border-strong': '#E8E0D0',
        divider: '#F5F0E8',
        success: '#5EA08C',
        warning: '#E8A87C',
        danger: '#DC6B6B',
      },
      fontFamily: {
        sans: ['"Noto Sans SC"', 'system-ui', '-apple-system', 'sans-serif'],
        serif: ['"Noto Serif SC"', 'Georgia', 'serif'],
      },
      fontSize: {
        '2xs': ['10px', { lineHeight: '14px' }],
        'xs': ['12px', { lineHeight: '18px' }],
        'sm': ['14px', { lineHeight: '22px' }],
        'base': ['16px', { lineHeight: '26px' }],
        'lg': ['18px', { lineHeight: '28px' }],
        'xl': ['20px', { lineHeight: '30px' }],
        '2xl': ['24px', { lineHeight: '36px' }],
        '3xl': ['30px', { lineHeight: '42px' }],
      },
      spacing: {
        '18': '4.5rem',
        '22': '5.5rem',
        '128': '32rem',
      },
      borderRadius: {
        'lg': '12px',
        'xl': '12px',
        '2xl': '16px',
        '3xl': '20px',
      },
      boxShadow: {
        'xs': '0 1px 2px rgba(0, 0, 0, 0.04)',
        'sm': '0 2px 8px rgba(0, 0, 0, 0.06)',
        'soft': '0 2px 8px rgba(0, 0, 0, 0.06)',
        'card': '0 4px 12px rgba(0, 0, 0, 0.08)',
        'md': '0 4px 12px rgba(0, 0, 0, 0.08)',
        'lg': '0 8px 24px rgba(0, 0, 0, 0.1)',
      },
    },
  },
  plugins: [],
};
